#include <errno.h>
#include <string.h>
#include <netdb.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <vector>
#include <string>

struct Member {
    std::string id;
    std::string name;
    std::string password;
};

// load members.txt file ( generated by AI )
std::vector<Member> load_Members_file(const char* filename)
{
    std::vector<Member> members;
    std::ifstream fin(filename);

    if (!fin) {
        std::cerr << "Cannot open " << filename << "\n";
        return members;
    }

    Member m;
    while (fin >> m.id >> m.name >> m.password) {
        members.push_back(m);
    }

    return members;
}

// For unencrypted password, get the encrypted version to compare with data in txt file. 
std::string encrypt(const std::string &pswd) {
    std::string encrypted;

    for (char c : pswd) {
        if (c >= 'A' && c <= 'Z') {
            encrypted += 'A' + (c - 'A' + 3) % 26;
        }
        else if (c >= 'a' && c <= 'z') {
            encrypted += 'a' + (c - 'a' + 3) % 26;
        }
        else if (c >= '0' && c <= '9') {
            encrypted += '0' + (c - '0' + 3) % 10;
        }
        else {
            encrypted += c; // special characters unchanged
        }
    }
    return encrypted;
}