#include <errno.h>
#include <string.h>
#include <netdb.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

// Struct to store data of space
struct Space {
    std::string lot;
    std::string usage[12];
};

// Load spaces.txt file ( generated by AI )
std::vector<Space> load_Spaces_file(const char* filename)
{
    std::vector<Space> spaces;
    std::ifstream fin(filename);

    if (!fin) {
        std::cerr << "Cannot open " << filename << "\n";
        return spaces;
    }

    while (true) {
        Space s;
        fin >> s.lot;
        if (!fin) break; // EOF

        for (int i = 0; i < 12; i++) {
            fin >> s.usage[i];
        }

        spaces.push_back(s);
    }

    return spaces;
}

// Find available time slots in corresponding parking lot.
std::string search_parking(std::vector<Space> spaces, std::string command){
    int k,z=0;
    std::string ret="";
    if (command == "search"){
        for(size_t i = 0; i<spaces.size(); i++){
            ret += spaces[i].lot;
            ret += ": Time slot(s)";
            for(int j = 0;j < 12; j++){
                if (spaces[i].usage[j] == "0"){
                    
                    z++;                                                
                    ret += " ";
                    ret += std::to_string(j+1);
                }
            }
            ret += "\n";
        }
        if(z == 0)ret = "NA";
    }
    else if(command == "search UPC"){
        for(size_t i = 0; i<spaces.size(); i++){
            k = 0;
            if(spaces[i].lot.substr(0,1) != "U")continue;
            for(int j = 0;j < 12; j++){
                if (spaces[i].usage[j] == "0"){
                    if (k == 0){
                        k++; 
                        z++;
                        ret += spaces[i].lot;
                        ret += ": Time slot(s)";
                    }
                    ret += " ";
                    ret += std::to_string(j+1);}
            }
            if (k!=0)ret += "\n";
        }
        if(z == 0)ret = "NA";
    }
    else if(command == "search HSC"){
        for(size_t i = 0; i<spaces.size(); i++){
            k = 0;
            if(spaces[i].lot.substr(0,1) != "H")continue;
            for(int j = 0;j < 12; j++){
                if (spaces[i].usage[j] == "0"){
                    if (k == 0){
                        k++; 
                        z++;
                        ret += spaces[i].lot;
                        ret += ": Time slot(s)";
                    }
                    ret += " ";
                    ret += std::to_string(j+1);}
            }
            if (k!=0)ret += "\n";
        }
        if(z == 0)ret = "NA";
    }
    else{
        ret = "WA";
    }
    
    return ret;
}

std::string lookup_parking(std::vector<Space> spaces, std::string id){
    int k,z=0;
    std::string ret="";
    
    for(size_t i = 0; i<spaces.size(); i++){
        k = 0;
        for(int j = 0;j < 12; j++){
            if (spaces[i].usage[j] == id){
                if (k == 0){
                    k++; 
                    z++;
                    ret += spaces[i].lot;
                    ret += ": Time slot(s)";
                }
                ret += " ";
                ret += std::to_string(j+1);}
        }
        if (k!=0)ret += "\n";
        }
    if(z == 0)ret = "NA";
    return ret;
}

std::string lookup_parking_price(std::vector<Space> spaces, std::string id){
    int k,z=0;
    std::string ret="";
    
    for(size_t i = 0; i<spaces.size(); i++){
        k = 0;
        for(int j = 0;j < 12; j++){
            if (spaces[i].usage[j] == id){
                if (k == 0){
                    k++; 
                    z++;
                    ret += spaces[i].lot;
                }
                ret += " ";
                ret += std::to_string(j+1);}
        }
        if (k!=0)ret += "\n";
        }
    if(z == 0)ret = "NA";
    return ret;
}

// Return all unavailable slots.
std::string reserve_parking(std::vector<Space> spaces, std::string command, std::string &available){
    size_t pos = command.find(" ");
    std::string space_code = command.substr(0, pos);
    std::string idx = command.substr(pos+1);
    std::string ret="";
    std::istringstream iss(idx);
    int k = 0;
    for (size_t i = 0; i<spaces.size(); i++){

        if (spaces[i].lot == space_code){
            k++;
            int x;// Check every time slot in corresponding code.
            while (iss>>x)
            { // Store every slot that is not zero which means not available.
                if (spaces[i].usage[x-1] != "0"){
                    ret += " " + std::to_string(x);
                }
                else{
                available += " " + std::to_string(x);  }
            }
        }
    }
    if (ret.empty())ret = "NA";
    if ( k == 0 )ret =idx;
    return ret;
}

// Change the parking lot reservation.
std::vector<Space> confirm_reserve(std::vector<Space> spaces, std::string command, std::string id){
    
    size_t pos = command.find(" ");
    std::string space_code = command.substr(0, pos);
    std::string idx = command.substr(pos+1);
    std::vector<Space> ret=spaces;
    std::istringstream iss(idx);

    for (size_t i = 0; i<spaces.size(); i++){
        if (spaces[i].lot == space_code){
            int x;// Check every time slot in corresponding code.
            while (iss>>x)
            { // Store every slot that is not zero which means not available.
                if (spaces[i].usage[x-1] == "0"){
                    ret[i].usage[x-1] = id;
                }   
            }
        }
    }
    return ret;
}

// Check if every slot is reserved by this id. True/False
bool check_parking(std::vector<Space> spaces, std::string command, std::string id){
    int k = 0;
    size_t pos = command.find(" ");
    std::string space_code = command.substr(0, pos);
    std::string idx = command.substr(pos+1);
    std::istringstream iss(idx);
    for (size_t i = 0; i<spaces.size(); i++){
        if (spaces[i].lot == space_code){
            k++;
            int x;// Check every time slot in corresponding code.
            while (iss>>x)
            { // check any slot that is not reserved by this id.
                if (spaces[i].usage[x-1] != id){
                    return false;
                }
            }
        }
    }
    if(k == 0)return false; // No such space code in the lot.
    return true;
}


// Cancel the parking lot reservation.
std::vector<Space> cancel_reserve(std::vector<Space> spaces, std::string command, std::string id){
    
    size_t pos = command.find(" ");
    std::string space_code = command.substr(0, pos);
    std::string idx = command.substr(pos+1);
    std::vector<Space> ret=spaces;
    std::istringstream iss(idx);

    for (size_t i = 0; i<spaces.size(); i++){
        if (spaces[i].lot == space_code){
            int x;// Check every time slot in corresponding code.
            while (iss>>x)
            { // Store every slot that is not zero which means not available.
                if (spaces[i].usage[x-1] == id){
                    ret[i].usage[x-1] = "0";
                }   
            }
        }
    }
    return ret;
}